# Generated by Django 3.1.3 on 2021-01-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_board_category_guestbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='ip_address',
            field=models.CharField(max_length=50),
        ),
    ]
