# Generated by Django 3.1.3 on 2021-01-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_auto_20210127_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
