# Generated by Django 3.1.3 on 2021-01-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_auto_20210127_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestbook',
            old_name='password',
            new_name='passwd',
        ),
    ]
