# Generated by Django 3.1.3 on 2021-01-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0011_auto_20210127_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='category_board', to='pybo.category'),
        ),
        migrations.AlterField(
            model_name='board',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
