# Generated by Django 3.1.3 on 2021-01-27 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0015_hitcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 27, 12, 39, 29, 750764, tzinfo=utc), null=True),
        ),
    ]
